baseURL: https://tristanchapman.netlify.app/
languageCode: en-us
title: Tristan's Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner: 
    buttonText: Get Started
    subtitle: Navigate this site to find out a little about me and my projects...
    title: Hi, my name is Tristan.
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park,NW1 4SA
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tchapman.mfa2022@london.edu
        title: 
    enable: yes
    phone:
      - phone: "07807107945"
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/tristanchapman98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/tristanchapman
  image: ''
  name: Tristan Chapman
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/aliquam
      - name: My CV
        url: blogs/CV
      - name: Yield Curve Project
        url: blogs/Yield
    menu: Menu
    subtitle: 
    title: Welcome to my website...
  tiles:
    enable: yes
    showcase:
      - image: profile.jpg
        subtitle: London Business School
        title: About me
        url: blogs/aliquam
      - image: photoday.jpeg
        subtitle: My Friends
        title: Photo Day
        url: blogs/tempus
      - image: lbs.jpeg
        subtitle: London Business School
        title: My CV
        url: blogs/CV
      #- image: pic04.jpg
        #subtitle: 
        #title: Ipsum
        #url: blogs/ipsum
      - image: image22.jpg
        subtitle: 
        title: Yield Curve Project
        url: blogs/Yield
     # - #image: pic06.jpg
        #subtitle: 
      #  title: 
     #   url: blogs/Drinks
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Navigate this site to see some of my work"
    title: My Site
    url: blogs









